### ISSUE TITLE
Is this hosted anywhere where end-users can play around with it?

### ISSUE THREAD

**Issue by theoryshaw** [dsx-tech/e-voting#4]
Is this hosted anywhere where end-users can play around with it?

**Comment by gm-dsxt** [comment]
No, now there is no sandbox or smth about it. It is research project for now, so if you want to use it to solve some cases, it is better to discuss cases and we can give some advices. So if you have any questions, please contact me.

**Comment by theoryshaw** [comment]
Thanks George...

No need to comment, but wanted to share the following ideas that might/might not spark some ideas (some of which, you might have thought about already)...

http://boards.straightdope.com/sdmb/showthread.php?t=517135

https://outlookzen.wordpress.com/2014/06/29/reinventing-democracy-the-google-way/

http://cckwpolitics.blogspot.com/2011/10/pagerank-politics-new-voting-system.html

Cheers.
